name: Python CI
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'python/**/*'
      - '**/*.py'
      - '**/*.toml'
      - .github/workflows/ci-python.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.2.1]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        shell: bash
        working-directory: ./python/backend
        run: ./scripts/install_python_deps.sh

      - name: Check Formatting
        working-directory: ./python/backend
        run: |
          poetry run poe format_check

      - name: Lint
        working-directory: ./python/backend
        run: |
          poetry run poe lint

      - name: Test
        working-directory: ./python/backend
        run: |
          poetry run poe test

      - name: Clean build cache
        working-directory: ./python/backend
        run: |
          rm -rf .venv && rm -rf .cache

      - name: Build and Publish Docker Container
        uses: darthtrevino/github-container-registry-build-push@main
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: showwhy-backend
          docker-image-tag:  latest
          dockerfile-path: ./python/backend/Dockerfile
          build-context: ./python/backend
          build-only: ${{ github.ref != 'refs/heads/main' }}
